// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Core__Array = require("@rescript/core/lib/js/src/Core__Array.bs.js");
var Connection__Download__Assets$AgdaModeVscode = require("./Connection__Download__Assets.bs.js");
var Connection__Download__Source$AgdaModeVscode = require("./Connection__Download__Source.bs.js");
var Connection__Download__DownloadArtifact$AgdaModeVscode = require("./Connection__Download__DownloadArtifact.bs.js");

async function sourceForSelection(memento, globalStorageUri, platformDeps, channel, platform, versionString, onEventOpt) {
  var onEvent = onEventOpt !== undefined ? onEventOpt : (function (param) {
        
      });
  var downloadPlatform = await platformDeps.determinePlatform();
  if (downloadPlatform.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: "CannotFindCompatibleALSRelease"
          };
  }
  var downloadPlatform$1 = downloadPlatform._0;
  var platformOk;
  platformOk = platform === "Wasm" ? true : Connection__Download__DownloadArtifact$AgdaModeVscode.Platform.matchesDownloadPlatform(platform, downloadPlatform$1);
  if (!platformOk) {
    return {
            TAG: "Error",
            _0: "CannotFindCompatibleALSRelease"
          };
  }
  var resolver = platformDeps.resolveDownloadChannel(channel, true);
  var error = await resolver(memento, globalStorageUri, downloadPlatform$1);
  if (error.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: error._0
          };
  }
  var source = error._0;
  if (source.TAG === "FromGitHub") {
    var descriptor = source._1;
    var release = descriptor.release;
    var assets;
    assets = platform === "Wasm" ? Connection__Download__Assets$AgdaModeVscode.wasm(release) : Connection__Download__Assets$AgdaModeVscode.nativeForPlatform(release, downloadPlatform$1);
    var matchingSource = Core__Array.reduce(assets, undefined, (function (found, asset) {
            if (found !== undefined) {
              return found;
            }
            var source_1 = {
              release: release,
              asset: asset,
              saveAsFileName: descriptor.saveAsFileName
            };
            var source = {
              TAG: "FromGitHub",
              _0: channel,
              _1: source_1
            };
            if (Connection__Download__Source$AgdaModeVscode.toVersionString(source) === versionString) {
              return source;
            }
            
          }));
    if (matchingSource !== undefined) {
      onEvent({
            TAG: "SourceResolved",
            _0: "GitHub",
            _1: Connection__Download__Source$AgdaModeVscode.toVersionString(matchingSource)
          });
      return {
              TAG: "Ok",
              _0: matchingSource
            };
    }
    if (platform === "Wasm") {
      return {
              TAG: "Error",
              _0: "CannotFindCompatibleALSRelease"
            };
    }
    var wasmAsset = Connection__Download__Assets$AgdaModeVscode.wasm(release)[0];
    if (wasmAsset === undefined) {
      return {
              TAG: "Error",
              _0: "CannotFindCompatibleALSRelease"
            };
    }
    var wasmSource_1 = {
      release: release,
      asset: wasmAsset,
      saveAsFileName: descriptor.saveAsFileName
    };
    var wasmSource = {
      TAG: "FromGitHub",
      _0: channel,
      _1: wasmSource_1
    };
    var wasmVersion = Connection__Download__Source$AgdaModeVscode.toVersionString(wasmSource);
    onEvent({
          TAG: "FallbackChosen",
          _0: wasmVersion
        });
    onEvent({
          TAG: "SourceResolved",
          _0: "GitHub",
          _1: wasmVersion
        });
    return {
            TAG: "Ok",
            _0: wasmSource
          };
  }
  onEvent({
        TAG: "SourceResolved",
        _0: "URL",
        _1: Connection__Download__Source$AgdaModeVscode.toVersionString(source)
      });
  return {
          TAG: "Ok",
          _0: source
        };
}

exports.sourceForSelection = sourceForSelection;
/* Connection__Download__Assets-AgdaModeVscode Not a pure module */
